package appjanicompiler;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Control.java
 *
 * Created on November 23, 2008, 5:59 PM
 */
import javax.swing.JOptionPane;



/**
 *
 * @author  hp
 */
public class Control extends javax.swing.JFrame {
    
    /** Creates new form Control */
    public Control() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JaNi Controller");

        jLabel1.setText(".class file:");

        jButton1.setLabel("OK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Search...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        // Quando o botão for clicado, chamar JANI com o caminho do arquivo .class
        // indicado na caixa de texto:
        String nClass = this.jTextField1.getText();
        if ( nClass.isEmpty() ){
            JOptionPane.showMessageDialog(null, "Nome inválido de arquivo .class.");
            return;
        }
        
        Process p;
        
        try {
            // Chamada para Windows:
            p = Runtime.getRuntime().exec("jani/jani-win.exe");//GEN-LAST:event_jButton1MouseClicked
        } catch (IOException ex) {
            // Caso tenha falhado, tentar chamada para Linux:
            try {
                p = Runtime.getRuntime().exec("jani/jani-lin.bin");
            } catch (IOException ex1) {
                // Em caso de nova falha, reportar o erro:
                JOptionPane.showMessageDialog(null, "Falha interna ao tentar executar JaNi!");
                p = null;
            }
        }
        
        if ( p == null ){
            JOptionPane.showMessageDialog(null, "Erro de execução na compilação.");
            return;
        }
        
        // Utilizar o processo para manipular o compilador
        try {
            p.getOutputStream().write(nClass.getBytes());
            p.getOutputStream().write('\n');
            p.getOutputStream().flush();
            
            //p.getOutputStream().write('\n');
            //p.getOutputStream().flush();
            
            p.getInputStream().close();
            p.waitFor();
            
            if ( p.exitValue() == 0 )
                JOptionPane.showMessageDialog(null, "Arquivo compilado com sucesso!");
            else JOptionPane.showMessageDialog(null, "Houve erros durante a compilação");
            
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(null, "Não será possível continuar. Uma falha (107) ocorreu.");
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Não será possível continuar. Uma falha (109) ocorreu.");
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Control().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
